import { Geist, Geist_Mono, Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from '@/lib/styled-registry'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ubuntuMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  subsets: ["latin"],
  weight: ["400", "700"], 


});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${ubuntuMono.variable} font-sans bg-white text-black`}>
       
         <StyledComponentsRegistry> 
          {children}
        </StyledComponentsRegistry> 
       
      </body>
    </html>
  );
}
